language: node.js
node_js:
  - 13
services:
  - docker
install:
  - echo "No installs..."
before_script:
  - echo "logging!!!"
script:
  - docker --version
  # building
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reserve_proxy
  # tagging
  - docker tag loui4/udagram-api-feed:v1
  - docker tag loui4/udagram-api-user:v1
  - docker tag loui4/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push loui4/udagram-api-feed:v1
  - docker push loui4/udagram-api-user:v1
  - docker push loui4/reverseproxy:v1
